SciPro ID: 2026SS_50

In [2]:
import numpy as np

# Overview

> **Objective:** Use a Generative AI system as an interactive tutor to review and practice fundamental **NumPy** concepts through guided explanations and small coding exercises.

## Background

Generative Artificial Intelligence (AI) systems can serve as personalized learning assistants by providing explanations, answering questions, generating practice tasks, and offering feedback on proposed solutions. In this task, a Generative AI tool (ChatGPT) is instructed to assume the role of a **NumPy tutor**. The AI guides the learning process by reviewing relevant concepts and creating one or two short programming exercises that the learner must solve independently.

## Relevance

The use of AI-supported tutoring aligns with contemporary approaches to computer science education, where intelligent systems facilitate:

- **Self-directed learning**
- **Personalized instruction**
- **Immediate feedback cycles**
- **Adaptive practice opportunities**

Consequently, Generative AI can complement traditional learning resources and enhance the effectiveness of programming education.

## ChatGPT Prompt:

"generate a coding exercise that include of the following topics:   
basic numpy functions and array operations  
creating and concatenating arrays of different sizes"

## AI Output:

# NumPy Array Builder Exercise

## Objective
Practice:
- Basic NumPy functions
- Array operations
- Creating arrays of different sizes
- Concatenating arrays

---

## Instructions

### Part 1: Create Arrays

1. Create a **1D NumPy array** containing the numbers `1` through `5`.

2. Create a **2D NumPy array** with shape `(2, 3)` containing any numbers you choose.

---

### Part 2: Basic NumPy Functions

Using the arrays you created, calculate and display:

- The **sum** of the 1D array
- The **mean** of the 1D array
- The **maximum value** in the 2D array

---

### Part 3: Array Operations

Perform at least **three** of the following operations on the 1D array:

- Addition
- Subtraction
- Multiplication
- Division

Display the result of each operation.

---

### Part 4: Create Arrays of Different Sizes

Create two additional arrays:

- Array A with shape `(2, 2)`
- Array B with shape `(2, 3)`

Fill them with any values you choose.

---

### Part 5: Concatenate Arrays

#### A. Concatenate 1D Arrays

Create another 1D array and concatenate it with your original 1D array.

#### B. Concatenate 2D Arrays

Concatenate two compatible 2D arrays:

- Along rows (`axis=0`) **or**
- Along columns (`axis=1`)

Display the resulting array.

---

### Part 6: Handling Errors

Attempt to concatenate two arrays whose dimensions are incompatible.

Use a `try`/`except` block to:

- Catch the error
- Print a helpful message explaining why the concatenation failed

Example:

```python
try:
    # concatenation code here
except ValueError as e:
    print("Concatenation failed:", e)
```

---

## Reflection Questions

Answer the following questions in markdown cells:

1. What happens when you try to add arrays of different shapes?

2. How is `np.concatenate()` different from element-wise operations such as addition or multiplication?

3. Why do some arrays concatenate successfully while others do not?

---

## Bonus Challenge

Create a function called `safe_concatenate()` that:

1. Accepts two NumPy arrays as input
2. Checks whether they can be concatenated
3. Returns the concatenated array if possible
4. Otherwise returns a helpful error message

Example:

```python
result = safe_concatenate(array1, array2)
print(result)
```

---

## Expected Output (Example)

```text
1D array: [1 2 3 4 5]

Sum: 15
Mean: 3.0

2D array:
[[1 2 3]
 [4 5 6]]

Max value: 6

Addition:
[2 3 4 5 6]

Multiplication:
[ 2  4  6  8 10]

Concatenated array:
[1 2 3 4 5 6 7]

Concatenation failed:
all the input array dimensions except for the concatenation axis must match exactly
```

## Solving the Tasks

#### 1: Creating 1D and 2D arrays

In [3]:
# 1D array
arr1 = np.array([1, 2, 3, 4, 5])

# 2D array with shape (2, 3)
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

print("1D array:", arr1)
print("2D array:\n", arr2)

1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]


#### 2: Basic NumPy Functions

In [4]:
sum_arr1 = np.sum(arr1)
mean_arr1 = np.mean(arr1)
max_arr2 = np.max(arr2)

print("Sum of 1D array:", sum_arr1)
print("Mean of 1D array:", mean_arr1)
print("Maximum value in 2D array:", max_arr2)

Sum of 1D array: 15
Mean of 1D array: 3.0
Maximum value in 2D array: 6


#### 3: Array Operations

In [5]:
add_result = arr1 + 2
sub_result = arr1 - 1
mul_result = arr1 * 3
div_result = arr1 / 2

print("Addition:", add_result)
print("Subtraction:", sub_result)
print("Multiplication:", mul_result)
print("Division:", div_result)

Addition: [3 4 5 6 7]
Subtraction: [0 1 2 3 4]
Multiplication: [ 3  6  9 12 15]
Division: [0.5 1.  1.5 2.  2.5]


#### 4: Create Arrays of Different Sizes

In [6]:
array_a = np.array([[1, 2],
                    [3, 4]])

array_b = np.array([[5, 6, 7],
                    [8, 9, 10]])

print("Array A:\n", array_a)
print("Shape of A:", array_a.shape)

print("Array B:\n", array_b)
print("Shape of B:", array_b.shape)

Array A:
 [[1 2]
 [3 4]]
Shape of A: (2, 2)
Array B:
 [[ 5  6  7]
 [ 8  9 10]]
Shape of B: (2, 3)


#### 5: Concatenate Arrays

In [7]:
arr1_extra = np.array([6, 7])
concat_1d = np.concatenate((arr1, arr1_extra))

print("Concatenated 1D array:", concat_1d)

Concatenated 1D array: [1 2 3 4 5 6 7]


In [9]:
array_c = np.array([[11, 12],
                    [13, 14]])

concat_2d_rows = np.concatenate((array_a, array_c), axis=0)

print("Concatenated 2D array along rows:\n", concat_2d_rows)

Concatenated 2D array along rows:
 [[ 1  2]
 [ 3  4]
 [11 12]
 [13 14]]


#### 6: Handle Errors for Incompatible Concatenation

In [10]:
try:
    # These arrays cannot be concatenated along axis=0 because their column counts differ
    bad_concat = np.concatenate((array_a, array_b), axis=0)
    print(bad_concat)
except ValueError as e:
    print("Concatenation failed:", e)

Concatenation failed: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3


#### 7: Reflection Questions

1. Adding arrays of different shapes may work only if NumPy can broadcast them together. Otherwise, it raises an error.

2. `np.concatenate()` joins arrays together along an axis. Element-wise operations like addition or multiplication act on matching elements instead of joining arrays.

3. Arrays concatenate successfully only when their dimensions match in all axes except the one being concatenated.

#### Bonus Challenge

In [11]:
def safe_concatenate(array1, array2, axis=0):
    try:
        result = np.concatenate((array1, array2), axis=axis)
        return result
    except ValueError as e:
        return f"Concatenation failed: {e}"

In [12]:
# Works
print(safe_concatenate(arr1, arr1_extra))

# Works
print(safe_concatenate(array_a, array_c, axis=0))

# Fails
print(safe_concatenate(array_a, array_b, axis=0))

[1 2 3 4 5 6 7]
[[ 1  2]
 [ 3  4]
 [11 12]
 [13 14]]
Concatenation failed: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3
